#!/usr/bin/env bash
#
# Builds the two host probes that answer whether sc68 3.0.0b is worth adopting.
#
# A probe, not a build: neither library is compiled the way Android compiles it, and neither result
# is a claim about a phone. What it does give is the same thirty files run through both libraries,
# which is the evidence `GOAL.md` round 5 item 1 asks for.
#
# sc68 3.0.0b needs three things autotools would have produced, all of them established by trial
# compile rather than guessed:
#
#   1. config.h            -- native/probe/sc68/generated/config.h, written by hand
#   2. file68_features.h   -- the tree ships a pre-generated one for MSVC; it is correct for us
#   3. sc68/trap68.h       -- 68000 machine code, assembled here by sc68's OWN assembler (as68,
#                             which is in the tree) and turned into a byte list, exactly as
#                             libsc68/Makefile.am does it
#
# Usage:  ./scripts/build-sc68-probes.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OLD="$ROOT/native/vendor/sc68"
NEW="$ROOT/native/vendor/sc68-3"
PROBE="$ROOT/native/probe/sc68"
BUILD="$PROBE/build"

[ -f "$OLD/api68/api68.c" ] || { echo "❌ sc68 2.2.1 missing. Run ./scripts/fetch-native-deps.sh"; exit 1; }
[ -f "$NEW/libsc68/src/api68.c" ] || { echo "❌ sc68 3.0.0b missing. Run ./scripts/fetch-sc68-svn.py"; exit 1; }

mkdir -p "$BUILD/obj-old" "$BUILD/obj-new" "$BUILD/gen/sc68"
cp "$PROBE/generated/config.h" "$BUILD/gen/config.h"
cp "$PROBE/generated/sc68/file68_features.h" "$BUILD/gen/sc68/file68_features.h"
# In both places: some sources include it as <sc68/file68_features.h> and others as
# "file68_features.h". Autoconf generates it into file68/sc68/ and puts that directory on the
# include path, which makes both spellings work; this reproduces that.
cp "$PROBE/generated/sc68/file68_features.h" "$BUILD/gen/file68_features.h"

echo "🔨 sc68 2.2.1 probe"
OLD_SRC=$(ls "$OLD"/emu68/*.c "$OLD"/io68/*.c "$OLD"/file68/*.c "$OLD"/api68/*.c "$OLD"/unice68/*.c 2>/dev/null | grep -v 'unice68/unice68\.c$')
export BUILD OLD
compile_old() {
    gcc -c -o "$BUILD/obj-old/$(echo "$1" | md5sum | cut -c1-16).o" "$1" \
        -I"$OLD" -w -DSC68_SHARED_DATA_PATH='""' -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 \
        -DHAVE_STDIO_H=1 -DHAVE_UNISTD_H=1 -DHAVE_GETENV=1
}
export -f compile_old
printf '%s\n' $OLD_SRC | xargs -P "$(nproc)" -I{} bash -c 'compile_old "$@"' _ {}
ar rcs "$BUILD/libsc68-old.a" "$BUILD"/obj-old/*.o
gcc -o "$PROBE/probe-2.2.1" "$PROBE/probe_2_2_1.c" "$BUILD/libsc68-old.a" -I"$OLD" -lm -w
echo "   ✅ $(ls "$BUILD"/obj-old/*.o | wc -l) objects"

echo "🔨 sc68 3.0.0b probe"

# as68 assembles the TOS trap emulator that api68.c embeds. Its own version.s is generated by
# configure from version.s.in; the numbers come from configure.ac and the pinned SVN revision.
gcc -o "$BUILD/as68" "$NEW"/as68/*.c -I"$BUILD/gen" -I"$NEW" -w -DHAVE_CONFIG_H=1
cat > "$NEW/libsc68/asm/version.s" <<'ASM'
;;; Generated by scripts/build-sc68-probes.sh. Numbers from configure.ac and the pinned revision.
MAJOR:	= 3
MINOR:	= 0
PATCH:	= 0
TWEAK:	= 713
VERNUM:	= (MAJOR<<28)+(MINOR<<20)+(PATCH<<12)+TWEAK
ASM
( cd "$NEW/libsc68" && "$BUILD/as68" asm/trapfunc.s -o "$BUILD/trapfunc.bin" >/dev/null )
hexdump -ve '1/1 "%d,\n"' "$BUILD/trapfunc.bin" > "$BUILD/gen/sc68/trap68.h"

# The source lists are the ones libsc68/*/Makefile.am declares, not a glob. Globbing picks up
# lines68.c (the monolithic alternative to the sixteen line files), cc68.c (which #errors that it is
# deprecated) and the two ym tables that are #included rather than compiled.
EMU="emu68 error68 getea68 inst68 ioplug68 mem68 line0_68 line1_68 line2_68 line3_68 line4_68 line5_68 line6_68 line7_68 line8_68 line9_68 lineA_68 lineB_68 lineC_68 lineD_68 lineE_68 lineF_68 table68"
IO="io68 mfp_io mfpemul mw_io mwemul paula_io paulaemul shifter_io ym_envel ym_blep ym_dump ym_io ym_puls ymemul"
# vfs68_ao and vfs68_curl are in the list even though libao and libcurl are off: they compile to
# stubs in that case, and init68.c calls their shutdown functions unconditionally. Dropping them as
# "not needed" is how this first failed to link.
F68="error68 file68 gzip68 ice68 init68 vfs68 vfs68_ao vfs68_curl vfs68_fd vfs68_file vfs68_mem vfs68_null vfs68_z msg68 option68 registry68 rsc68 string68 timedb68 uri68"

NEW_SRC=""
for f in $EMU; do NEW_SRC="$NEW_SRC $NEW/libsc68/emu68/$f.c"; done
for f in $IO;  do NEW_SRC="$NEW_SRC $NEW/libsc68/io68/$f.c"; done
for f in $F68; do NEW_SRC="$NEW_SRC $NEW/file68/src/$f.c"; done
NEW_SRC="$NEW_SRC $NEW/libsc68/src/api68.c $NEW/libsc68/src/conf68.c $NEW/libsc68/src/libsc68.c $NEW/libsc68/src/mixer68.c"
# dial68 is new in 3.x: a small dialogue/config module that api68.c calls into from sc68_cntl.
# Not optional -- the link fails without it. 2.2.1 had no equivalent.
NEW_SRC="$NEW_SRC $NEW/libsc68/dial68/dial68.c $NEW/libsc68/dial68/dial_conf.c $NEW/libsc68/dial68/dial_tsel.c $NEW/libsc68/dial68/dial_finf.c"
NEW_SRC="$NEW_SRC $NEW/unice68/unice68_pack.c $NEW/unice68/unice68_unpack.c $NEW/unice68/unice68_version.c"

NEW_INC="-I$BUILD/gen -I$NEW -I$NEW/libsc68 -I$NEW/libsc68/emu68 -I$NEW/libsc68/io68 -I$NEW/libsc68/sc68 -I$NEW/file68 -I$NEW/file68/sc68 -I$NEW/unice68"
export NEW_INC
compile_new() {
    gcc -c -o "$BUILD/obj-new/$(echo "$1" | md5sum | cut -c1-16).o" "$1" -DHAVE_CONFIG_H=1 $NEW_INC -w
}
export -f compile_new
printf '%s\n' $NEW_SRC | xargs -P "$(nproc)" -I{} bash -c 'compile_new "$@"' _ {}
ar rcs "$BUILD/libsc68-new.a" "$BUILD"/obj-new/*.o
gcc -o "$PROBE/probe-3.0.0b" "$PROBE/probe_3_0_0b.c" "$BUILD/libsc68-new.a" $NEW_INC -lm -w

# A second build with assertions off, which is how a release APK compiles. sc68 3.x asserts on an
# MFP timer mode it does not support and then handles it anyway (mfpemul.c sets the timer to zero
# and continues), so the two builds answer different questions: this one says what a user would
# hear, the one above says what a debug build would do to them.
echo "🔨 sc68 3.0.0b probe (NDEBUG, as a release build compiles)"
mkdir -p "$BUILD/obj-ndebug"
compile_ndebug() {
    gcc -c -o "$BUILD/obj-ndebug/$(echo "$1" | md5sum | cut -c1-16).o" "$1" -DHAVE_CONFIG_H=1 -DNDEBUG=1 $NEW_INC -w
}
export -f compile_ndebug
printf '%s\n' $NEW_SRC | xargs -P "$(nproc)" -I{} bash -c 'compile_ndebug "$@"' _ {}
ar rcs "$BUILD/libsc68-ndebug.a" "$BUILD"/obj-ndebug/*.o
gcc -o "$PROBE/probe-3.0.0b-ndebug" "$PROBE/probe_3_0_0b.c" "$BUILD/libsc68-ndebug.a" $NEW_INC -DNDEBUG=1 -lm -w
echo "   ✅ $(ls "$BUILD"/obj-ndebug/*.o | wc -l) objects"
echo "   ✅ $(ls "$BUILD"/obj-new/*.o | wc -l) objects"

echo
echo "Both probes built. Now: ./scripts/probe-sc68.py"
