// SPDX-FileCopyrightText: 2026 Przunk
// SPDX-License-Identifier: GPL-3.0-or-later

package com.przunk.protracktor.data

/**
 * songdb's song lengths, as parsing and nothing else (`docs/PLAN_SONGDB_LENGTHS.md`, A52).
 *
 * **The Amiga formats' lengths.** A replay routine has no notion of how long a tune is and the file
 * states nothing, so without this a tune UADE plays shows no total until a second emulator has run
 * it to the end — and a tune that loops never shows one. songdb was generated by audacious-uade,
 * the same UADE on the same files: measured 2026-09-21, it has a length for all 3,792 Modland files
 * the app offers through UADE, agreeing with the app's own measurement to a tenth of a second.
 *
 * GPL-2.0-or-later, like the metadata table beside it (`docs/LICENSES.md`).
 *
 * **No Android imports**, for [SongDbMetadata]'s reason: twelve megabytes of somebody else's text
 * format is the thing to test on the JVM.
 *
 * ### The file
 *
 * ```
 * 001a02867da0\t0\t128240,l 5840,s 3360,s 3340,s 3060,s
 * ff5c7b3227e0\t0\t65920,p 65920,p,!
 * ```
 *
 * The first twelve hex characters of the MD5, the number of the first subsong (0 or 1), then one
 * `milliseconds,end` per subsong in order; a third field of `!` marks a subsong that duplicates
 * another.
 *
 * ### Kept as published, interpreted when read
 *
 * [parse] validates a row and keeps its subsong text exactly as it came. [subsongs] and [lengths]
 * decide what the end codes mean, at the moment a file is opened. A change of policy — which ends
 * count as a length, what to do with an empty subsong — is then a change here and not a
 * re-download of twelve megabytes.
 */
object SongDbLengths {

    /** How many hex characters of the MD5 the published database keys on — as [SongDbMetadata]. */
    const val KEY_LENGTH = 12

    /**
     * How a subsong ended when audacious-uade measured it.
     *
     * Read from `audacious-uade/src/common/songend.h`, not guessed from the letters: `status_string`
     * there names every one, and the file's codes are their initials.
     */
    enum class End(val code: String, val isLength: Boolean) {
        /** The replay routine reported the end. */
        PLAYER("p", true),
        /** The routine's end, with trailing silence trimmed. */
        PLAYER_SILENCE("p+s", true),
        /** The routine's end, with a fade trimmed. */
        PLAYER_VOLUME("p+v", true),
        /** Sound stopped and stayed stopped. */
        SILENCE("s", true),
        /** A loop was detected; the length is one pass through it (`docs/PLAN_SONGDB_LENGTHS.md` D4). */
        LOOP("l", true),
        LOOP_SILENCE("l+s", true),
        LOOP_VOLUME("l+v", true),
        /** A repeat was detected. */
        REPEAT("r", true),
        /** Faded out. */
        VOLUME("v", true),
        /** The subsong makes no sound. Not a length: an empty subsong (plan D3, for later). */
        NO_SOUND("n", false),
        /** Measuring failed. */
        ERROR("e", false),
        /**
         * The measurement gave up at a cap. **Not a length**, and this is the one that matters: a
         * cap reported as a length is how 19 of 140 tunes came out exactly 512 seconds long in
         * A44, and how every console tune claimed 2:30 in C67.
         */
        TIMEOUT("t", false),
        /** A code this build does not know. Refused rather than guessed at. */
        UNKNOWN("?", false);

        companion object {
            private val byCode = entries.associateBy { it.code }
            fun of(code: String): End = byCode[code] ?: UNKNOWN
        }
    }

    data class Subsong(val seconds: Double, val end: End, val duplicate: Boolean) {
        /** Whether this is a length the player may show, seek within and end the tune at. */
        val isLength: Boolean get() = end.isLength && seconds > 0.0
    }

    /** One row as stored: the key as a number, the first subsong, and the text as published. */
    data class Row(val key: Long, val firstSubsong: Int, val subsongs: String)

    /**
     * Every well-formed row, **lazily** — 476,919 of them, and [SongDbMetadata.parse] says what
     * materialising a file this size costs on a phone.
     *
     * A row is refused whole when its key is not twelve hex characters, its first subsong is not a
     * number, or not one of its subsongs parses: a lookup table must not acquire entries nothing
     * will match, nor half a file's subsongs in the wrong places.
     */
    fun parse(lines: Sequence<String>): Sequence<Row> = lines.mapNotNull { line ->
        val fields = line.trimEnd('\r', '\n').split('\t')
        if (fields.size < 3) return@mapNotNull null
        val key = keyOf(fields[0].trim()) ?: return@mapNotNull null
        val first = fields[1].trim().toIntOrNull() ?: return@mapNotNull null
        val text = fields[2].trim()
        if (text.isEmpty() || subsongsOrNull(text) == null) return@mapNotNull null
        Row(key, first, text)
    }

    /** The same, for text already in memory. Used by the tests, not by the import. */
    fun parse(text: String): List<Row> = parse(text.lineSequence()).toList()

    /** Every subsong of a stored row, in order. Empty if the text is not what [parse] accepted. */
    fun subsongs(text: String): List<Subsong> = subsongsOrNull(text).orEmpty()

    /**
     * The lengths the player may use, one per subsong in order, **0.0 where there is none**.
     *
     * Zero rather than a gap, because the caller indexes this by subsong: the fourth entry must
     * belong to the fourth subsong whether or not the third has a length. Zero is what the rest of
     * the app already reads as "unknown" (C68).
     */
    fun lengths(text: String): List<Double> =
        subsongs(text).map { if (it.isLength) it.seconds else 0.0 }

    /**
     * The key for a file: the first twelve characters of its MD5, **as a number**.
     *
     * As a number because that halves the table: measured on the full file, a twelve-character text
     * key takes 25.0 MB in SQLite and the same 48 bits as an `INTEGER PRIMARY KEY` — which is the
     * rowid, and needs no separate index — take 11.1 MB. Null for anything that is not hex.
     */
    fun keyOf(md5: String): Long? {
        val prefix = md5.trim().lowercase().take(KEY_LENGTH)
        if (prefix.length != KEY_LENGTH || !prefix.all { it in "0123456789abcdef" }) return null
        return prefix.toLong(16)
    }

    private fun subsongsOrNull(text: String): List<Subsong>? =
        text.split(' ').filter { it.isNotEmpty() }.map { part ->
            val bits = part.split(',')
            if (bits.size < 2) return null
            val millis = bits[0].toLongOrNull() ?: return null
            if (millis < 0) return null
            Subsong(
                seconds = millis / 1000.0,
                end = End.of(bits[1]),
                duplicate = bits.getOrNull(2) == "!",
            )
        }.takeIf { it.isNotEmpty() }
}
